/* Shared helpers: API access, nav, badges, citation linkification. */

/* js/config.js sets STATIC_DATA = true for the GitHub Pages build, where the
   live API is replaced by a static JSON snapshot under api/ (regenerated by
   scripts/export_static.py from the curated database). List-endpoint filters
   are then applied client-side with the same semantics as the backend. */

async function apiGet(path, params = {}) {
    if (typeof STATIC_DATA !== "undefined" && STATIC_DATA) {
        return staticApiGet(path, params);
    }
    const qs = new URLSearchParams(
        Object.entries(params).filter(([, v]) => v !== null && v !== undefined && v !== "")
    ).toString();
    const url = "/api" + path + (qs ? `?${qs}` : "");
    const res = await fetch(url);
    if (!res.ok) {
        let detail = res.statusText;
        try { detail = (await res.json()).detail || detail; } catch (e) { /* non-JSON */ }
        throw new Error(`API ${res.status}: ${detail}`);
    }
    return res.json();
}

const STATIC_FILES = {
    "/stats": "api/stats.json",
    "/evidence_tiers": "api/evidence_tiers.json",
    "/drugs": "api/drugs.json",
    "/cell_lines": "api/cell_lines.json",
    "/modifiers": "api/modifiers.json",
    "/interactions": "api/interactions.json",
    "/explorer/matrix": "api/explorer_matrix.json",
    "/scoring/models": "api/scoring_models.json",
    "/prediction/readiness": "api/prediction_readiness.json",
    "/coverage-gaps": "api/coverage_gaps.json",
    "/prioritization/methodology": "api/prioritization_methodology.json",
    "/opportunity/cell-lines": "api/opportunity_cell_lines.json",
    "/opportunity/cancer-types": "api/opportunity_cancer_types.json",
};

async function staticApiGet(path, params = {}) {
    const detail = path.match(/^\/(cell_lines|modifiers|interactions|drugs)\/([^/]+)$/);
    const file = detail ? `api/${detail[1]}/${detail[2]}.json` : STATIC_FILES[path];
    if (!file) throw new Error(`No static snapshot for ${path}`);
    const res = await fetch(file);
    if (!res.ok) throw new Error(`Static data ${res.status} for ${file}`);
    const data = await res.json();
    if (path === "/explorer/matrix") {
        return data.by_drug[params.drug_id] || {
            drug: null, drug_class: params.drug_class || null,
            cell_lines: [], modifiers: [], cells: [],
            evidence_tier_definitions: data.evidence_tier_definitions,
        };
    }
    // /interactions/candidates matches the generic per-id detail pattern
    // (same file layout as api/interactions/<uuid>.json), but it's a list
    // that still needs its own query-param filtering/sorting applied
    // client-side, same as the live backend does server-side.
    if (path === "/interactions/candidates") {
        return applyCandidateParams(data, params);
    }
    return detail ? data : filterStaticList(path, data, params);
}

function applyCandidateParams(rows, params) {
    let out = rows;
    if (params.drug_id) out = out.filter((it) => it.drug_id === params.drug_id);
    if (params.cell_line_id) out = out.filter((it) => it.cell_line_id === params.cell_line_id);
    if (params.tissue_origin) {
        const t = String(params.tissue_origin).toLowerCase();
        out = out.filter((it) => (it.tissue_origin || "").toLowerCase().includes(t));
    }
    if (params.low_resource_relevance !== undefined && params.low_resource_relevance !== "") {
        const want = params.low_resource_relevance === true || params.low_resource_relevance === "true";
        out = out.filter((it) => it.low_resource_relevance === want);
    }
    out = [...out];
    if (params.sort === "priority_score") {
        out.sort((a, b) => b.priority_score - a.priority_score);
    } else {
        out.sort((a, b) =>
            (a.drug_name || "").localeCompare(b.drug_name || "") ||
            (a.cell_line_name || "").localeCompare(b.cell_line_name || "") ||
            (a.modifier_agent || "").localeCompare(b.modifier_agent || ""));
    }
    return out;
}

function filterStaticList(path, rows, params) {
    const ci = (s) => String(s ?? "").toLowerCase();
    if (path === "/cell_lines") {
        const q = ci(params.q), tissue = ci(params.tissue), mut = ci(params.mutation);
        return rows.filter((cl) =>
            (!q || ci(cl.name).includes(q) || ci(cl.tissue_origin).includes(q) || ci(cl.cancer_subtype).includes(q)) &&
            (!tissue || ci(cl.tissue_origin).includes(tissue)) &&
            (!mut || ci(JSON.stringify(cl.key_mutations || [])).includes(mut)));
    }
    if (path === "/modifiers") {
        const q = ci(params.q);
        return rows.filter((m) =>
            (!params.modifier_type || m.modifier_type === params.modifier_type) &&
            (!q || ci(m.agent).includes(q)));
    }
    if (path === "/interactions") {
        const keys = ["cell_line_id", "modifier_id", "drug_id", "evidence_tier", "interaction_type", "modifier_type"];
        return rows.filter((it) => keys.every((k) => !params[k] || it[k] === params[k]) &&
            (params.low_resource_relevance === undefined || params.low_resource_relevance === "" ||
             it.low_resource_relevance === (params.low_resource_relevance === true || params.low_resource_relevance === "true")));
    }
    return rows;
}

function escapeHtml(s) {
    return String(s ?? "").replace(/[&<>"']/g, (c) => ({
        "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
}

/* ---------- nav ---------- */

const NAV_ITEMS = [
    { href: "index.html", label: "Home" },
    { href: "explorer.html", label: "Explorer" },
    { href: "cell-lines.html", label: "Cell Lines" },
    { href: "modifiers.html", label: "Modifiers" },
    { href: "drugs.html", label: "Drugs" },
    { href: "candidates.html", label: "Candidates" },
    { href: "coverage.html", label: "Coverage Gaps" },
    { href: "scoring.html", label: "Scoring" },
];

function renderNav(active) {
    const links = NAV_ITEMS.map((i) => {
        const cls = i.label === active
            ? "text-emerald-400 font-semibold"
            : "text-slate-300 hover:text-white";
        return `<a class="${cls} px-3 py-2 text-sm" href="${i.href}">${i.label}</a>`;
    }).join("");
    const el = document.getElementById("nav");
    if (!el) return;
    el.innerHTML = `
      <header class="bg-slate-900 border-b border-slate-800 sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
          <a href="index.html" class="flex items-center gap-2">
            <i class="fa-solid fa-circle-nodes text-emerald-400 text-xl"></i>
            <div>
              <div class="text-white font-bold leading-tight">NPxP</div>
              <div class="text-slate-400 text-xs">Non-Pharm × Pharm — drug × modifier interactions in cancer cell lines</div>
            </div>
          </a>
          <nav class="flex items-center">${links}</nav>
        </div>
      </header>`;
}

/* ---------- badges ---------- */

const TYPE_STYLES = {
    synergistic: { cls: "bg-rose-500", label: "Synergistic" },
    additive: { cls: "bg-amber-500", label: "Additive" },
    antagonistic: { cls: "bg-sky-500", label: "Antagonistic" },
    unknown: { cls: "bg-slate-500", label: "Unknown" },
};
const TIER_SHORT = {
    tier_1_direct: "T1",
    tier_2_inferred: "T2",
    tier_2b_model_predicted: "T2b",
    tier_2c_nearest_neighbor: "T2c",
    tier_3_mechanism_only: "T3",
    tier_4_heuristic_target_match: "T4",
};
const TIER_STYLES = {
    tier_1_direct: "bg-emerald-600",
    tier_2_inferred: "bg-yellow-600",
    tier_2b_model_predicted: "bg-violet-600",
    tier_2c_nearest_neighbor: "bg-indigo-600",
    tier_3_mechanism_only: "bg-orange-700",
    tier_4_heuristic_target_match: "bg-red-800",
};

function typeBadge(t) {
    const s = TYPE_STYLES[t] || TYPE_STYLES.unknown;
    return `<span class="${s.cls} text-white text-xs font-semibold px-2 py-0.5 rounded-full">${s.label}</span>`;
}
function tierBadge(t) {
    const cls = TIER_STYLES[t] || "bg-slate-600";
    return `<span class="${cls} text-white text-xs font-semibold px-2 py-0.5 rounded-full">${TIER_SHORT[t] || "?"}</span>`;
}

/* ---------- citations ---------- */

function citationHref(c) {
    if (c.startsWith("pmid:")) return ["https://pubmed.ncbi.nlm.nih.gov/" + c.slice(5), "PMID " + c.slice(5)];
    if (c.startsWith("doi:")) return ["https://doi.org/" + c.slice(4), "doi:" + c.slice(4)];
    if (c.startsWith("geo:")) return ["https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=" + c.slice(4), "GEO " + c.slice(4)];
    return [null, c];
}

function citationChips(citations) {
    return (citations || []).map((c) => {
        const [href, label] = citationHref(c);
        if (!href) return `<span class="cite-chip">${escapeHtml(label)}</span>`;
        return `<a class="cite-chip" target="_blank" rel="noopener" href="${href}">${escapeHtml(label)} <i class="fa-solid fa-arrow-up-right-from-square text-[0.6rem]"></i></a>`;
    }).join("");
}

/* ---------- misc ---------- */

function protocolKv(params) {
    const entries = Object.entries(params || {});
    if (!entries.length) return '<div class="text-slate-500 text-sm">No protocol parameters recorded.</div>';
    return entries.map(([k, v]) =>
        `<div><div class="kv-key">${escapeHtml(k)}</div><div class="kv-val">${escapeHtml(v)}</div></div>`
    ).join("");
}

function mutationChips(muts) {
    return (muts || []).map((m) =>
        `<span class="cite-chip">${escapeHtml(m.gene)}${m.variant ? ` · ${escapeHtml(m.variant)}` : ""}</span>`
    ).join("");
}

/* ---------- Celligner tumor-concordance (build spec v3) ---------- */

const CONCORDANCE_LABEL = {
    good_model: "Good tumor model",
    poor_model_mesenchymal_shift: "Poor model (mesenchymal shift)",
    unassessed: "Unassessed",
};
const CONCORDANCE_STYLE = {
    good_model: "bg-emerald-600",
    poor_model_mesenchymal_shift: "bg-rose-700",
    unassessed: "bg-slate-600",
};

/* ---------- low-resource relevance (build spec v6) ---------- */

function lowResourceBadge(isRelevant) {
    if (!isRelevant) return "";
    return `<span class="bg-teal-600 text-white text-xs font-semibold px-2 py-0.5 rounded-full" title="Both the drug (essential/generic) and the modifier (minimal/low infrastructure) qualify as low-resource-setting relevant"><i class="fa-solid fa-globe mr-1"></i>Low-resource relevant</span>`;
}

function concordanceBadge(flag, score) {
    const cls = CONCORDANCE_STYLE[flag] || "bg-slate-600";
    const label = CONCORDANCE_LABEL[flag] || flag || "Unassessed";
    const scoreText = (score === null || score === undefined) ? "" : ` (${Number(score).toFixed(2)})`;
    return `<span class="${cls} text-white text-xs font-semibold px-2 py-0.5 rounded-full" title="Celligner tumor-transcriptome concordance">${escapeHtml(label)}${escapeHtml(scoreText)}</span>`;
}
